name: Build and Upload Docker

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Container
      run: |
        docker build . -t craftamap/pluploader:${{ github.event.release.tag_name }} --build-arg PL_VERSION=${{ github.event.release.tag_name }}
